name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.1.3
repository: https://github.com/zino-app/graphql-flutter/tree/main/packages/graphql
issue_tracker: https://github.com/zino-hofmann/graphql-flutter/issues

dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  gql: ^1.0.0+1
  gql_exec: ^1.0.0+1
  gql_link: ^1.0.0
  gql_http_link: ^1.1.0
  gql_transform_link: ^1.0.0
  gql_error_link: ^1.0.0+1
  gql_dedupe_link: ^2.0.3+1
  hive: ^2.1.0
  normalize: ^0.9.1
  http: ^1.2.1
  collection: ^1.15.0
  web_socket_channel: ^3.0.1
  stream_channel: ^2.1.0
  rxdart: ^0.27.1
  uuid: ^4.4.0

dev_dependencies:
  async: ^2.5.0
  mockito: ^5.0.0
  test: ^1.16.0
  coverage: ^1.0.3
  http_parser: ^4.0.0
  lints: ^1.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
